# Generated by Django 5.2 on 2025-06-17 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_activitylog_project_activitylog_metadata_and_more'),
        ('projects', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project'),
        ),
    ]
